FROM debian:jessie

RUN apt-get update
RUN apt-get install libgconf-2-4 -y
RUN apt-get install libnss3-dev -y
RUN apt-get install libasound2 -y
RUN apt-get install libxtst6 -y
RUN apt-get install libnotify4  -y
RUN apt-get install xvfb -y
RUN apt-get install libxss1 -y

# Create the jenkins user
RUN useradd -d "/var/jenkins_home" -u 1000 -m -s /bin/bash jenkins

# Create the folders and volume mount points
RUN mkdir -p /var/log/jenkins
RUN chown -R jenkins:jenkins /var/log/jenkins
VOLUME ["/var/log/jenkins", "/var/jenkins_home"]

USER jenkins
CMD ["echo", "Data container for Jenkins"]